<?php
/**
 * Application bootstrap
 *
 * @author Adam Faulkner <adzfaulkner@hotmail.com>
 */
// requires the vendor autoload file generated by composer
require __DIR__ . '/../vendor/autoload.php';
// obtains the pimple container
require __DIR__ . '/container.php';

$app = new Silex\Application();
$app->register(new Silex\Provider\ServiceControllerServiceProvider());

$app['controller.music'] = function (\Silex\Application $app) use ($app, $container) {
    return new \Baboon\Controller\Music(
        $container['service.music.music'],
        $app['request_stack']
    );
};
